import "~/styles/globals.css";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { cookies } from "next/headers";
import "reflect-metadata";
import { DEFAULT_APP_THEME } from "~/constants/constants";
import RootLayout from "~/features/root/layout";
import ThemeProvider from "~/providers/Theme.Provider";
import { TRPCReactProvider } from "~/trpc/react";
import type { AppTheme } from "~/types/types";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootAppLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const cookie = await cookies();
  const theme =
    (cookie.get("theme")?.value as AppTheme | null) ?? DEFAULT_APP_THEME;
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <AntdRegistry>
          <TRPCReactProvider>
            <ThemeProvider theme={theme}>
              <RootLayout>{children}</RootLayout>
            </ThemeProvider>
          </TRPCReactProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
