import "~/styles/globals.css";

import { AntdRegistry } from "@ant-design/nextjs-registry";
import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { cookies } from "next/headers";
import "reflect-metadata";
import ThemeProvider from "~/providers/Theme.Provider";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const cookie = await cookies();
  const theme =
    (cookie.get("theme")?.value as ("dark" | "light") | null) ?? "light";
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>
        <AntdRegistry>
          <TRPCReactProvider>
            <ThemeProvider theme={theme}>{children}</ThemeProvider>
          </TRPCReactProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
